const Joi = require('@hapi/joi');

const finanzasValidation = (data) => {
    const schema = Joi.object({
        operacion: Joi.string().required(),
        fecha: Joi.date(),
        noPagos: Joi.number(),
        peridiocidad: Joi.string().max(100),
        referencia: Joi.string().max(50),
        dePara: Joi.string().max(100),
        descripcion: Joi.string().max(50),
        persona: Joi.string().max(100),
        promotor: Joi.string().max(100),
        tfiva: Joi.string().max(50),
        iva: Joi.number(),
        tfseguro: Joi.string().max(50),
        compania: Joi.string().max(50),
        prima: Joi.number(),
        fpago: Joi.number(),
        poliza: Joi.string().max(100),
        tfSegFin: Joi.string().max(100),
        vigInicio: Joi.string().max(100),
        vigFinal: Joi.string().max(100),
        tipoUnidad: Joi.string().max(100),
        fechaPago: Joi.date(),
        relPago: Joi.string().max(100),
        siniestros: Joi.string().max(100),
        cantPolizas: Joi.string().max(100),
        sigVenc: Joi.string().max(100),
        vAsegurado: Joi.string().max(100),
        tipo: Joi.string().max(100),
        marca: Joi.string().max(100),
        serie: Joi.string().max(100),
        modelo: Joi.string().max(100),
        factura: Joi.string().max(100),
        version: Joi.string().max(100),
        motor: Joi.string().max(100),
        lote: Joi.string().max(100),
        comision: Joi.string().max(100),
        importe: Joi.string().max(100),
        producto: Joi.string().max(100),
        fondeador: Joi.string().max(100),
        valorOperacion: Joi.number(),
        tipoFin: Joi.number(),
        anticipo: Joi.number(),
        seguroDeuda: Joi.number(),
        apertura: Joi.number(),
        deposito: Joi.number(),
        admon: Joi.number(),
        gps: Joi.number(),
        seguroAuto: Joi.number(),
        vRescate: Joi.number(),
        descuento: Joi.number(),
        chequera: Joi.string().max(100),
        ctroCosto: Joi.string().max(100),
        folio: Joi.string().max(100),
        lineaVta: Joi.string().max(100),
        comentarios: Joi.string().max(255),
        estatus: Joi.string().max(100),
        cancelado: Joi.string().max(100),
        idCliente: Joi.string().max(100),
        ffzc: Joi.string().max(100),
        ffzi: Joi.string().max(100),
        ffzg: Joi.string().max(100),
        ffza: Joi.string().max(100),
        empresa: Joi.string().max(100),
        lineaVenta: Joi.string().max(100),
        aplicaPagos: Joi.string().max(100),
        fFondeo: Joi.string().max(100)
    });

    return schema.validate(data);
};

module.exports.finanzasValidation = finanzasValidation;